#!/bin/sh
#
# @name Custom model
#
# @type Custom
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
#
# @maintainer John Doe <johndoe@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults

# Define custom airframe parameters below.

# We select multirotor for now but this could potentially
# be custom.
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.15
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.15
param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.15
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.15
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104


# We initiate the MAVLink connection from vehicle with sysid 2 to the vehicle with sysid 3.
udp_local_port_mav2=17002
udp_local_port_mav3=17003
if param compare MAV_SYS_ID 2
then
	mavlink start -u $udp_local_port_mav2 -r 400000 -m custom -o $udp_local_port_mav3
	mavlink stream -r 10 -s ATTITUDE_TARGET -u $udp_local_port_mav2

elif param compare MAV_SYS_ID 3
then
	mavlink start -u $udp_local_port_mav3 -r 400000 -m custom -o $udp_local_port_mav2
	mavlink stream -r 10 -s ATTITUDE_TARGET -u $udp_local_port_mav3
fi
