#!/bin/sh
#
# @name Custom quadcopter
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.45
param set-default CA_ROTOR0_PY 0.45
param set-default CA_ROTOR1_PX -0.45
param set-default CA_ROTOR1_PY 0.45
param set-default CA_ROTOR2_PX -0.45
param set-default CA_ROTOR2_PY -0.45
param set-default CA_ROTOR3_PX 0.45
param set-default CA_ROTOR3_PY -0.45

param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_KM 0.05

param set-default PWM_AUX_FUNC1 101
param set-default PWM_AUX_FUNC2 102
param set-default PWM_AUX_FUNC3 103
param set-default PWM_AUX_FUNC4 104

param set-default PWM_AUX_DIS1 1000
param set-default PWM_AUX_DIS2 1000
param set-default PWM_AUX_DIS3 1000
param set-default PWM_AUX_DIS4 1000
param set-default PWM_AUX_MIN1 1100
param set-default PWM_AUX_MIN2 1100
param set-default PWM_AUX_MIN3 1100
param set-default PWM_AUX_MIN4 1100
param set-default PWM_AUX_MAX1 2000
param set-default PWM_AUX_MAX2 2000
param set-default PWM_AUX_MAX3 2000
param set-default PWM_AUX_MAX4 2000

param set-default SENS_BOARD_Y_OFF 10.0

param set-default EKF2_IMU_POS_X 0.005
param set-default EKF2_IMU_POS_Y 0.0
param set-default EKF2_IMU_POS_Z 0.034
